spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://49.232.212.48:3306/gulimall_pms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 49.232.212.48:8848
