spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://49.232.212.48:3306/gulimall_sms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 49.232.212.48:8848



#开启feign对sentinel的支持
feign:
  sentinel:
    enabled: true

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml

  #\u8BBE\u7F6E\u5B9E\u4F53\u7C7B\u7684\u81EA\u589E\u4E3B\u952E
  global-config:
    db-config:
      id-type: auto

#暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: '*'

